meta:
  environment: (( merge ))
  instances: 1
  dns_root: (( merge ))
  security_groups: (( merge ))
  network_name: (( merge ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: buildbox_z1
    instances: (( meta.instances ))
    networks:
      - name: (( meta.network_name ))

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: (( meta.network_name ))
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
