meta:
  environment: ~
  access_token: (( merge ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: buildbox_z1
    template: buildbox
    instances: 1
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties:
      buildbox:
        access_token: (( meta.access_token ))

networks: (( merge ))

properties: {}
